config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :chapters
  root :to => "chapters#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :description, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= simple_form_for @chapter, :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :content, as: 'ckeditor' %>

  <%= f.button :submit, :class => 'btn-primary', label: false %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                chapters_path, :class => 'btn btn-default' %>
<% end %>

app/views/chapters/edit.html.erb
<%- model_class = Chapter -%>
<%= render :partial => 'form' %>

app/views/chapters/index.html.erb
<%- model_class = Chapter -%>

<% if @chapters.empty? %>
<%= link_to "Clique aqui p/ começar", new_chapter_path, class: "btn btn-default pull-right" %>
  <h1>Nada por aqui</h1>
  <p>Vamos começar criando um primeiro capitulo?!</p>
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= link_to chapter.title, chapter_path(chapter) %></td>
        <td><%=l chapter.updated_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      chapter_path(chapter), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_chapter_path(chapter), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      chapter_path(chapter),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/chapters/new.html.erb
<%- model_class = Chapter -%>

<%= render :partial => 'form' %>

app/views/chapters/show.html.erb
<%- model_class = Chapter -%>
<div class="page-header">
  <div class="pull-right">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  chapters_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_chapter_path(@chapter), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  chapter_path(@chapter),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>

  </div>
  <h1><%= @chapter.title %></h1>
  <span><%= @chapter.description %></span>
</div>
  <div class="container">
    <%= @chapter.content %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Notaril" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>


    <%- model_class = Chapter -%>
    <div class="page-header">
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_chapter_path,
                  :class => 'btn btn-primary btn-lg pull-right' %>

      <h1>Notaril <small><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></small></h1>
      <div class="navbar navbar-default navbar-fixed">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
                <li><%= link_to model_class.model_name.human.pluralize.titleize , chapters_path  %></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "Sair" , destroy_user_session_path  %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-offset-1 col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>